# -*- coding: utf-8 -*-
from pathlib import Path
from html import escape
from urllib.parse import urlsplit
from product_details import DETAILS
from nurse_board import NURSE_BOARD
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
products=[
 dict(id='cursay',name='Cursay',category='macOS 음성 입력',title='쓰던 앱에<br>말로 입력하세요.',short='말한 내용을 텍스트로 바꿔 현재 사용 중인 앱에 입력하는 macOS 앱입니다.',stage='개발 중',intro='메신저나 메모 앱에서 입력할 곳을 선택하고 말해 보세요. Cursay가 음성을 텍스트로 바꿔 그곳에 입력합니다. 변환된 문장을 따로 복사해 붙여 넣을 필요가 없습니다.',features=[('말하는 동안 바로 입력','말하는 동안 인식된 문장을 입력란에 넣습니다. 녹음을 마칠 때까지 기다리지 않고 입력 내용을 확인할 수 있습니다.'),('입력할 곳을 고정','현재 선택한 입력란에 쓰거나, 특정 입력란을 고정해 쓸 수 있습니다. 고정 모드에서는 다른 앱으로 이동해도 원래 입력란에 입력합니다.'),('음성 명령','설정한 명령어를 말하면 엔터 같은 키 입력을 실행합니다. 글을 입력하다가 같은 방식으로 명령을 사용할 수 있습니다.')],steps=[('입력할 곳 선택','메신저나 편집기 등 글을 쓸 입력란을 선택합니다.'),('단축키를 누르고 말하기','fn 키로 음성 입력을 시작합니다. 입력할 곳을 고정하는 모드도 지원합니다.'),('입력된 문장 확인','말한 내용을 확인하고 필요한 부분을 직접 다듬습니다.')],note='현재 macOS용으로 개발 중입니다. 공개 다운로드는 준비 중이며, 음성 인식 서비스 연결과 마이크·손쉬운 사용 권한이 필요합니다.',faq=[('모든 처리가 Mac 안에서 이루어지나요?','아니요. 현재 음성 인식은 외부 서비스 연결을 사용합니다. 오프라인 전용 제품은 아닙니다.'),('지금 다운로드할 수 있나요?','현재는 개발 단계입니다. 일반 사용자를 위한 설치 파일과 배포 절차를 준비하고 있습니다.')]),
 dict(id='jjikgo',name='찍고',category='도장 · 서명 · 문서',title='문서에 도장과<br>서명을 넣으세요.',short='PDF나 이미지에 도장·서명을 넣고 저장하는 웹 도구입니다. 문서를 출력해서 날인한 뒤 다시 스캔하지 않아도 됩니다.',stage='개발 중',intro='찍고는 견적서, 신청서, 계약서에 도장이나 서명 이미지를 넣는 웹 도구입니다. 브라우저에서 문서를 열고 위치와 크기를 맞춘 뒤 완성된 파일을 저장합니다.',features=[('도장과 서명 준비','문서에 넣을 도장이나 서명 이미지를 준비합니다.'),('문서 위에 직접 배치','PDF 또는 이미지를 열고 필요한 위치에 도장·서명을 올립니다. 위치와 크기를 확인하며 문서를 마무리합니다.'),('완성본 미리보기와 저장','저장 전에 도장·서명이 들어간 위치를 확인하고, 완성된 문서를 파일로 내려받습니다.')],steps=[('문서 열기','도장이나 서명을 넣을 PDF 또는 이미지를 선택합니다.'),('도장·서명 배치','문서에서 필요한 곳에 올리고 위치와 크기를 맞춥니다.'),('확인 후 저장','미리보기에서 내용을 확인하고 완성본을 내려받습니다.')],note='웹 서비스로 개발 중입니다. PDF·이미지 작업을 중심으로 만들고 있으며, HWP·HWPX·DOCX 원본 저장은 검증 중입니다.',faq=[('인증서 기반 전자서명 서비스인가요?','찍고는 문서에 도장·서명 이미지를 배치하는 도구입니다. 본인 인증이나 전자서명 인증서 발급 기능은 제공하지 않습니다.'),('어떤 파일을 열 수 있나요?','PDF와 이미지를 중심으로 개발하고 있습니다. 다른 문서 형식의 원본 저장 지원은 아직 확정되지 않았습니다.')]),
 dict(id='yeoun',name='여운',category='대화형 꿈 해석',title='꿈을 적으면<br>대화로 해석합니다.',short='꿈 내용을 입력하면 해석을 받고, 궁금한 장면에 대해 추가로 질문할 수 있습니다.',stage='개발 중',intro='여운은 꿈 내용과 당시의 감정을 바탕으로 해석하는 대화형 서비스입니다. 기억나는 장면을 적고 해석을 읽은 뒤, 더 알고 싶은 부분을 질문할 수 있습니다.',features=[('꿈 내용 입력','기억나는 장면이나 등장인물, 꿈에서 느낀 감정을 적습니다. 순서가 정확하지 않아도 대화를 시작할 수 있습니다.'),('장면과 감정을 바탕으로 해석','꿈에 나온 소재뿐 아니라 사건의 순서와 그때 느낀 감정도 함께 살펴봅니다.'),('추가 질문','해석에서 이해되지 않는 부분을 질문하거나, 기억난 내용을 덧붙여 대화를 이어갈 수 있습니다.')],steps=[('꿈 이야기 남기기','기억에 남은 장면과 감정을 말하듯 적습니다.'),('해석 읽어보기','입력한 꿈과 감정에 대한 해석을 읽습니다.'),('질문 이어가기','궁금한 장면이나 감정에 대해 대화를 이어갑니다.')],note='현재 개발 중인 서비스입니다. 꿈 해석은 자기 성찰을 위한 참고 콘텐츠이며, 미래의 사건을 예측하거나 의학적 진단을 제공하지 않습니다.',faq=[('좋은 꿈인지 나쁜 꿈인지 알려주나요?','좋은 꿈이나 나쁜 꿈으로 단정하지 않습니다. 어떤 장면이었는지, 어떤 감정이 들었는지, 최근 경험과 관련이 있는지를 함께 살펴봅니다.'),('지금 이용하거나 결제할 수 있나요?','현재 서비스와 이용 흐름을 개발하고 있습니다. 이 페이지는 제품 소개이며 이용·결제를 제공하지 않습니다.')]),
 dict(id='moru',name='Moru',category='AI 작업 공간',title='AI와 대화하며<br>파일을 편집하세요.',short='AI 모델을 연결해 파일을 읽고 수정하며, 필요한 도구를 실행하는 작업 공간입니다.',stage='연구·개발',intro='Moru는 내 컴퓨터에서 실행하는 AI 작업 공간입니다. 사용할 모델을 연결한 뒤 대화로 작업을 요청하고, 작업 폴더의 파일과 실행 결과를 확인할 수 있습니다.',features=[('모델 연결','모델 제공자와 사용할 모델을 선택합니다. 대화 중 모델을 변경하면 다음 요청부터 적용됩니다.'),('작업 폴더의 파일 편집','대화마다 작업 폴더를 두고 파일을 읽거나 수정합니다. AI가 작성한 문서와 코드를 작업 공간에서 확인할 수 있습니다.'),('도구 추가','작업에 필요한 도구를 추가하고 실행 코드를 수정할 수 있습니다. 변경한 도구를 이후 작업에 사용하는 방식을 연구하고 있습니다.')],steps=[('모델 연결','사용할 모델 제공자와 연결 방식을 설정합니다.'),('작업 요청','새 대화에서 원하는 결과와 작업할 내용을 전달합니다.'),('파일과 결과 확인','수정된 파일과 도구 실행 결과를 확인하고, 필요한 수정을 다시 요청합니다.')],note='개발자·고급 사용자를 위한 연구·개발 프로젝트입니다. 로컬 작업 공간에서 실행되지만, 선택한 모델에 따라 외부 API와 네트워크 연결을 사용합니다.',faq=[('인터넷 없이 쓸 수 있는 AI인가요?','로컬 실행은 작업 공간이 내 컴퓨터에서 동작한다는 뜻입니다. 모델 연결 방식에 따라 외부 서비스와 인터넷이 필요하며, 모든 추론의 오프라인 실행을 보장하지 않습니다.'),('일반 사용자를 위한 완성 제품인가요?','아직 연구·개발 중입니다. 실행하려면 설치와 모델 설정이 필요하며, 일반 사용자용 설치 파일은 공개하지 않았습니다.')])
]

for product in products:
 product.update(DETAILS[product["id"]])
products.insert(0, NURSE_BOARD)
for product in products:
 repo = {"nurse-board":"nurse-board-web", "yeoun":"yeoun", "jjikgo":"jjikgo"}.get(product["id"])
 if repo:
  product["links"].append({"url":f"https://github.com/dhjin1125/{repo}","label":f"{product['name']} GitHub","state":"소스 코드와 실행 안내"})


def mark(): return '<span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i><i></i></span>'
def header(): return f'<a class="skip" href="#main">본문 바로가기</a><header class="header wrap"><a class="brand" href="/" aria-label="노드오프 홈">{mark()}nodeoff</a><nav aria-label="주요 메뉴"><a href="/#products">제품</a><a href="/#studio">스튜디오</a><a class="nav-action" href="/#products">제품 둘러보기 <span aria-hidden="true">↗</span></a></nav></header>'
def footer(): return f'<footer class="footer wrap"><a class="brand" href="/">{mark()}nodeoff</a><p>앱·웹 서비스 개발<br><a class="contact-email" href="mailto:jin@nodeoff.kr">jin@nodeoff.kr</a></p><small>© 2026 NODEOFF · <a href="https://github.com/dhjin1125/nodeoff-company" target="_blank" rel="noopener noreferrer">GitHub</a></small><a href="#main" class="top-link">맨 위로 ↑</a></footer>'
def preview(pid):
 if pid=='nurse-board': return '<div class="nurse-window"><div class="nurse-top"><b>Nurse Board</b><span>채용 탐색</span></div><p class="nurse-search">지역 · 경력 · 근무 형태로 찾기</p><div class="nurse-tags"><span>서울·경기</span><span>간호 직무</span><span>주간 근무</span></div><div class="nurse-job"><small>공고 예시</small><strong>내 조건에 맞는 간호 일자리</strong><p>지원 자격과 근무 조건 확인</p><div class="nurse-line"></div><span>공고 원문 보기 ↗</span></div></div>'
 if pid=='cursay':
  bars=''.join(f'<i style="--h:{n}px"></i>' for n in [12,22,35,19,42,29,16,34,23,11,25,39,18,30,13])
  return f'<div class="voice-note"><span class="window-label"><b>● ● ●</b> 새로운 메모</span><p>내일 오후 세 시에<br>회의가 있습니다.<span class="caret"></span></p><div class="note-lines"></div></div><div class="voice-capsule"><span class="mic-icon">◉</span><div class="wave">{bars}</div><span class="key">fn</span></div><span class="float-label">음성 입력 예시</span>'
 if pid=='jjikgo': return '<div class="paper"><span class="paper-label">DOCUMENT / 01</span><h4>업무 협의서</h4><div class="paper-lines"></div><div class="paper-lines short"></div><p class="paper-sign">확인 및 서명 <span>(인)</span></p><div class="seal">노드<br>오프</div></div><div class="stamp-tools"><span>✎ 서명</span><span class="selected">▧ 도장</span><span>↧ 저장</span></div>'
 if pid=='yeoun': return '<img src="/assets/yeoun-moon.webp" width="960" height="960" alt="" loading="lazy"><div class="dream-question">달로 이어진 계단을<br>걷는 꿈을 꿨어요.</div><div class="dream-answer"><span>여운</span>그때 어떤 기분이 들었나요?</div>'
 return '<div class="moru-window"><div class="moru-top"><b>moru</b><span>새로운 작업　＋</span></div><div class="moru-content"><div class="moru-side">작업 공간<span>▤ notes.md</span><span>▤ ideas.md</span><span>⌘ tools</span></div><div class="moru-chat"><p>이 아이디어를 문서로 정리해 줘.</p><div class="tool-result"><span>↳ 파일 작업</span><strong>ideas.md</strong><i></i><i></i><i></i></div><div class="moru-input">작업 내용 입력 <b>↑</b></div></div></div></div>'
def stage(p,extra=''): return f'<div class="product-stage {p["id"]} {extra}"><div class="stage-art" aria-hidden="true">{preview(p["id"])}</div><span class="preview-label">기능 예시</span></div>'
def head(title,desc,path): return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f8f9f7"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="https://nodeoff.kr{path}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="https://nodeoff.kr{path}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"></head><body>'''

def external_link(link, label=None, cls='text-link'):
 return f'<a class="{cls}" href="{escape(link["url"], quote=True)}" target="_blank" rel="noopener noreferrer">{escape(label or link["label"])} <span aria-hidden="true">↗</span><span class="sr-only"> (새 창)</span></a>'

def access_section(p):
 links=''.join(f'<li>{external_link(link)}<span class="link-state">{link["state"]}</span><span class="link-host">{urlsplit(link["url"]).netloc}</span></li>' for link in p['links'])
 return f'<section class="access-section wrap" id="access"><div><p class="eyebrow">접속 및 배포 상태</p><h2>{p["link_status"]}</h2><p class="access-note">{p["link_note"]}</p></div>'+(f'<ul class="access-links">{links}</ul>' if links else '<p class="access-empty">제품 기능과 사용 방법을 아래에 정리했습니다.</p>')+'</section>'

cards='' 
for i,p in enumerate(products):
 cards+=f'<article class="product-card" id="{p["id"]}"><a class="product-link" href="/products/{p["id"]}" aria-label="{p["name"]} 자세히 보기">{stage(p)}<div class="product-heading"><h3>{p["name"]}</h3><span class="round-arrow" aria-hidden="true">↗</span></div><p class="product-category">{p["category"]}<span>{p["stage"]}</span></p><h4>{p["title"]}</h4><p class="product-summary">{p["short"]}</p><span class="text-link">제품 자세히 보기 <span aria-hidden="true">→</span></span></a>'
 if p["links"]:
  cards+='<div class="card-access">'+external_link(p["links"][0],p.get("card_link_label", "개발 미리보기"))+f'<p>{p["link_note"]}</p></div>'
 cards+='</article>'
body=f'''{header()}<main id="main"><section class="hero wrap"><div class="hero-text"><p class="eyebrow"><span class="live-dot"></span> 소프트웨어 개발 스튜디오</p><h1>노드오프의<br><span>앱과 웹 서비스.</span></h1><p class="hero-description">음성 입력 앱부터 문서 편집 도구까지.<br>직접 기획하고 개발하는 제품을 소개합니다.</p><a class="button" href="#products">제품 소개 <span aria-hidden="true">↓</span></a></div><div class="hero-object" aria-hidden="true"><div class="hero-tile tile-voice"><div class="mini-wave">{''.join(f'<i style="--h:{n}px"></i>' for n in [26,48,68,38,84,56,32])}</div><span>Cursay</span></div><div class="hero-tile tile-stamp"><div class="hero-seal">찍고</div><span>도장·서명 문서 도구</span></div><div class="hero-tile tile-dream"><img src="/assets/yeoun-moon.webp" alt="" width="960" height="960"><span>여운</span></div><div class="hero-tile tile-moru"><b>m<span>↗</span></b><span>Moru</span></div></div></section><section class="products wrap" id="products"><div class="section-heading"><div><p class="eyebrow">제품 소개</p><h2>만들고 운영하는<br>제품</h2></div><p>각 제품을 누르면 주요 기능과<br>사용 방법을 자세히 볼 수 있습니다.</p></div><div class="product-grid">{cards}</div><p class="collection-note">초기 운영 중인 서비스와 개발 중인 제품입니다. 각 제품 페이지에서 기능과 현재 상태를 확인할 수 있습니다.</p></section><section class="studio" id="studio"><div class="wrap studio-grid"><div><p class="eyebrow">ABOUT NODEOFF</p><h2>노드오프 소개</h2><p>노드오프는 인천에 있는 소프트웨어 개발 스튜디오입니다.<br class="desktop-only"> 데스크톱 앱과 웹 서비스를 기획하고 개발합니다.</p><div class="studio-sign">nodeoff<span>Apps & web services</span></div></div><dl class="facts"><div><dt>상호</dt><dd>노드오프</dd></div><div><dt>대표</dt><dd>진동현</dd></div><div><dt>사업 분야</dt><dd>응용 소프트웨어 개발 및 공급업</dd></div><div><dt>사업자등록번호</dt><dd>502-60-03676</dd></div><div><dt>시작한 날</dt><dd>2026년 9월 10일</dd></div><div><dt>지역</dt><dd>인천광역시</dd></div><div><dt>문의</dt><dd><a class="contact-email" href="mailto:jin@nodeoff.kr">jin@nodeoff.kr</a></dd></div></dl></div></section></main>{footer()}'''
(OUT/'index.html').write_text(head('노드오프 — 앱·웹 서비스 개발','Nurse Board, Cursay, 찍고, 여운, Moru. 노드오프가 개발·운영하는 앱과 웹 서비스의 기능, 사용 방법, 현재 상태를 소개합니다.','/')+body+'</body></html>')
for idx,p in enumerate(products):
 features=''.join(f'<article><span class="feature-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate(p['features']))
 steps=''.join(f'<li><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></li>' for i,(t,d) in enumerate(p['steps']))
 uses=''.join(f'<article><h3>{t}</h3><p>{d}</p></article>' for t,d in p['usecases'])
 specs=''.join(f'<div><dt>{t}</dt><dd>{d}</dd></div>' for t,d in p['specs'])
 hero_action=(external_link(p['links'][0], p.get('action_label', '개발 버전 보기'), 'button')+'<a class="text-link" href="#features">기능 살펴보기 ↓</a>') if p['links'] else '<a class="button" href="#features">기능 살펴보기 <span aria-hidden="true">↓</span></a>'
 faqs=''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in p['faq'])
 nxt=products[(idx+1)%len(products)]
 body=f'''{header()}<main id="main"><section class="detail-hero wrap"><a class="back-link" href="/#products">← 모든 제품</a><div class="detail-top"><div><p class="eyebrow">{p['category']} <span class="status">{p['stage']}</span></p><p class="detail-name">{p['name']}</p><h1>{p['title']}</h1><p class="detail-intro">{p['intro']}</p><div class="detail-actions">{hero_action}</div><p class="hero-availability">{p["link_status"]} · <a href="#access">접속 안내</a></p></div><figure>{stage(p)}<figcaption>기능을 설명하기 위한 구성입니다.</figcaption></figure></div></section>{access_section(p)}<section class="detail-section wrap"><div class="detail-heading"><p class="eyebrow">활용 예시</p><h2>이런 작업에 사용할 수 있습니다</h2></div><div class="usecase-grid">{uses}</div></section><section class="detail-section wrap" id="features"><div class="detail-heading"><p class="eyebrow">제품 안내</p><h2>주요 기능</h2></div><div class="feature-grid">{features}</div></section><section class="flow-section"><div class="wrap flow-grid"><div><p class="eyebrow">사용 흐름</p><h2>사용 방법</h2><p>기본적인 사용 순서입니다.</p></div><ol class="steps">{steps}</ol></div></section><section class="detail-section wrap spec-grid"><div><p class="eyebrow">사용 전 확인</p><h2>지원 환경과 제한 사항</h2></div><dl class="product-specs">{specs}</dl></section><section class="detail-section wrap info-grid"><div><p class="eyebrow">현재 단계</p><h2>{p['stage']}</h2><p class="availability">{p['note']}</p></div><div class="faq"><h2>자주 묻는 질문</h2>{faqs}</div></section><aside class="next-product wrap" aria-label="다른 제품"><div><p class="eyebrow">다른 제품 보기</p><a href="/products/{nxt['id']}">{nxt['name']} <span aria-hidden="true">↗</span></a><p>{nxt['category']}</p></div><a class="text-link" href="/#products">전체 제품 보기 →</a></aside></main>{footer()}'''
 (OUT/'products'/f'{p["id"]}.html').write_text(head(f'{p["name"]} — 노드오프',p['short'],f'/products/{p["id"]}')+body+'</body></html>')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://nodeoff.kr{p}</loc></url>' for p in ['/']+[f'/products/{p["id"]}' for p in products])+'</urlset>')
print(f'Generated homepage, {len(products)} product pages, and sitemap.')
